name: record
description: Audio recorder from microphone to file or stream with multiple codecs, bit rate and sampling rate options.
version: 5.1.1
homepage: https://github.com/llfbandit/record/tree/master/record

environment:
  sdk: ^3.3.0
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/uuid
  uuid: ">=3.0.7 <5.0.0"

  record_platform_interface: ^1.1.0
  record_web: ^1.0.4
  record_windows: ^1.0.2
  record_linux: '>=0.5.0 <1.0.0'

#  record_android: ^1.2.2
#  record_darwin: ^1.1.0

  record_darwin:
    git:
      url: https://github.com/ihdream72/record.git
#      ref: 6cea5189e240ea3fcb601fcdb39a3e037c11ff89
#      ref: 1bfe73ba5726c724417537d46a6421ce8bce6540
      ref: 8596111e767ad339a92f0b3e62aae52e506c0a3e
      path: record_darwin

  record_android:
    git:
      url: https://github.com/ihdream72/record.git
      ref: 92d67a4d9f0934541ae6e2a8cf7db7c15ab464b5
      path: record_android

dev_dependencies:
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^4.0.0

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        default_package: record_android
      ios:
        default_package: record_darwin
      web:
        default_package: record_web
      windows:
        default_package: record_windows
      macos:
        default_package: record_darwin
      linux:
        default_package: record_linux
